### ISSUE TITLE
Add more information on how not to hit Cloudflare protection

### ISSUE THREAD

**Issue by mrnossiom** [rx342/senscritique2letterboxd#3]
Hi,

In order for the script to work for me, I had to add a dummy User Agent in the headers, or else I would hit Sens Critique's Cloudflare DDoS protection. I think this is a protection they added after the release of this tool.

I would suggest to either add a User Agent in the `requests.post()` headers or simply precise this in the README.

The script worked perfectly well. Would recommend!

Thanks

**Comment by rx342** [comment]
Hey, thank you a lot for the feedback! I opened a PR #4, can you tell me if this is what you had in mind?
